import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import styles from "../styles/Home.module.scss";

interface HomeProps {
  token: string;
}

const Home: NextPage<HomeProps> = ({ token }) => {
  const [data, setData] = useState<any>({});

  async function fetchData() {
    const response = await fetch("/api/me");
    const data = await response.json();

    console.log({ data });
    setData(data);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Spotify API</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <pre>
          <code>{JSON.stringify(data, null, 2)}</code>
        </pre>
        <button onClick={fetchData}>fetch</button>
      </main>
    </div>
  );
};

export default Home;

export async function getStaticProps() {
  const token = process.env.SPOTIFY_TOKEN as string;

  return {
    props: { token },
  };
}
